/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-02-18 17:35:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SingleJob_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/single_Job_Desc.css\" /> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <nav>Navigation Bar</nav>\r\n");
      out.write("  <div id=\"custom-layout\">\r\n");
      out.write("    <div class=\"custom-middle\">\r\n");
      out.write("      <div class=\"custom-middle-sub\">\r\n");
      out.write("        <div class=\"company-name-logo\">\r\n");
      out.write("          <div class=\"company-name\">\r\n");
      out.write("            <h4 class=\"job-title\">\r\n");
      out.write("              Executive Directior - Effortless Income - Any Age/ Experience\r\n");
      out.write("              <br />\r\n");
      out.write("              Join Team WFH\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"company-name\">Perfect Publishing Solutions</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img class=\"company-logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/mastercard.jfif\" alt=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Job-basic-details\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/suitcase.png\" alt=\"NA\" class=\"location\" />\r\n");
      out.write("          <div class=\"year-exp\">\r\n");
      out.write("            <p class=\"details\">&nbsp;&nbsp;0-5 Yrs&nbsp;&nbsp;</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <p>|</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"salary\">\r\n");
      out.write("            <p>&nbsp;&nbsp;Rs&nbsp;&nbsp;4000000&nbsp;&nbsp;</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <p>|</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/location.png\" alt=\"NA\" class=\"location\" />\r\n");
      out.write("          <div class=\"location-name\">\r\n");
      out.write("            <p>&nbsp;&nbsp;Temp. WFH - Mumbai</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <div class=\"opening-class\">\r\n");
      out.write("          <div class=\"info-about-job\">\r\n");
      out.write("            <div class=\"posted\">Posted:&nbsp;</div>\r\n");
      out.write("            <div>26 days ago&nbsp;&nbsp;&nbsp;&nbsp;</div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <p>|</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"opening\">&nbsp;&nbsp;&nbsp;&nbsp;Opening: &nbsp;</div>\r\n");
      out.write("            <div>5&nbsp;&nbsp;&nbsp;&nbsp;</div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <p>|</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"applicant\">\r\n");
      out.write("              &nbsp;&nbsp;&nbsp;&nbsp;applicant: &nbsp;\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>321</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"login-container\">\r\n");
      out.write("            <button class=\"button-17\" id=\"Login-to-apply\" role=\"button\">\r\n");
      out.write("              Login to apply\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"custom-middle-sub\">\r\n");
      out.write("        <h5 class=\"Job-description\">Job description</h5>\r\n");
      out.write("        <div class=\"hr-email\">\r\n");
      out.write("          apply directly hr.knte@gmail.com\r\n");
      out.write("          <p>\r\n");
      out.write("            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum\r\n");
      out.write("            aliquam vel cupiditate ratione aperiam dolores amet nobis iure\r\n");
      out.write("            unde impedit laboriosam consequuntur, nulla nesciunt nihil\r\n");
      out.write("            mollitia error. Tenetur, officia quaerat.\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <h5 class=\"required-candidate-profile\">Required Candidate profile</h5>\r\n");
      out.write("        <div class=\"required-candidate-profile-details\">\r\n");
      out.write("          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorum\r\n");
      out.write("          aliquam vel cupiditate ratione aperiam dolores amet nobis iure unde\r\n");
      out.write("          impedit laboriosam consequuntur, nulla nesciunt nihil mollitia\r\n");
      out.write("          error. Tenetur, officia quaerat.\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"about-role\">\r\n");
      out.write("          <h5 class=\"role\">Role:&nbsp;</h5>\r\n");
      out.write("          <div class=\"role-details\">Strategic & Top Management - Other</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"about-industry\">\r\n");
      out.write("          <h5 class=\"Industry\">Industry-type:&nbsp;</h5>\r\n");
      out.write("          <div class=\"Industry-details\">Management Consulting</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"about-department\">\r\n");
      out.write("          <h5 class=\"department\">Department:&nbsp;</h5>\r\n");
      out.write("          <div class=\"department-details\">Strategic & Top Management</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"about-Employment\">\r\n");
      out.write("          <h5 class=\"employment\">Employment Type:&nbsp;</h5>\r\n");
      out.write("          <div class=\"employment-details\">Strategic & Top Management</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"about-role-category\">\r\n");
      out.write("          <h5 class=\"role-category\">Role-Category:&nbsp;</h5>\r\n");
      out.write("          <div class=\"role-category-details\">Strategic & Top Management</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <h5 class=\"education\">Education:</h5>\r\n");
      out.write("        <div class=\"about-UG\">\r\n");
      out.write("          <h5 class=\"UG\">UG:&nbsp;</h5>\r\n");
      out.write("          <div class=\"UG-details\">BTECH / BE in Civil</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <h5 class=\"key-skills\">Key skills:</h5>\r\n");
      out.write("        <div class=\"about-key-skills\">\r\n");
      out.write("          <div class=\"key-skills-details\">\r\n");
      out.write("            Skill Highlighted with * are preferred keyskills\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"key-skills-container\">\r\n");
      out.write("          <button class=\"Infrastructure\" id=\"Infrastructure\" role=\"button\">\r\n");
      out.write("             * Infrastructure\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"Infrastructure\" id=\"Highway-Project\" role=\"button\">\r\n");
      out.write("            Highway Project\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"Infrastructure\" id=\"Road-project\" role=\"button\">\r\n");
      out.write("            Road Project\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"Infrastructure\" id=\"Strategic-Planning\" role=\"button\">\r\n");
      out.write("            Strategic Planning\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"Infrastructure\" id=\"Financal-Management\" role=\"button\">\r\n");
      out.write("            Financal Management\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"social-media-container\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/facebook.png\" alt=\"NA\" class=\"social-media\" />\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/twitter.png\" alt=\"NA\" class=\"social-media\" />\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/linkedin.png\" alt=\"NA\" class=\"social-media\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"custom-middle-sub\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <h5 class=\"about-company\">About company:&nbsp;</h5>\r\n");
      out.write("          <div class=\"about-company-details\">ICICI Bank LTD</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <h5 class=\"company-role\">Company role</h5>\r\n");
      out.write("        <div class=\"about-company-role\">\r\n");
      out.write("          <h5 class=\"address\">Address:&nbsp;</h5>\r\n");
      out.write("          <div class=\"company-role-details\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni\r\n");
      out.write("            perferendis.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"custom-middle-sub\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <h5 class=\"imposter\">Beaware of imposter:&nbsp;</h5>\r\n");
      out.write("          <div class=\"imposter-details\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("            Dignissimos optio, cupiditate fuga eveniet Lorem ipsum, dolor sit\r\n");
      out.write("            amet consectetur adipisicing elit. Dolores ut facere error\r\n");
      out.write("            inventore. Veritatis accusantium, quaerat esse, facere numquam\r\n");
      out.write("            assumenda vero commodi ab nihil ut sint! Consequuntur accusamus\r\n");
      out.write("            saepe hic?\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"custom-right\">\r\n");
      out.write("      <div class=\"custom-right-sub\" id=\"custom-right-sub\">\r\n");
      out.write("        <h4 class=\"right-container-headings\">\r\n");
      out.write("          Job you might be intrested in\r\n");
      out.write("        </h4>\r\n");
      out.write("        <div class=\"all-about-intrested-job\">\r\n");
      out.write("          <div class=\"company-name-job-name\">\r\n");
      out.write("            <h5 class=\"job-name-of-intrested-job\">\r\n");
      out.write("              Business Development Executive:&nbsp;\r\n");
      out.write("            </h5>\r\n");
      out.write("            <h5 class=\"company-name-of-intrested-comp\">ICICI Bank</h5>\r\n");
      out.write("            <div class=\"Job-basic-details\">\r\n");
      out.write("              <div class=\"rating\">\r\n");
      out.write("                <label></label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h6 class=\"Review\">4.0 | 335223 Review</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"intrested-job-logo-div\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/netflix.png\" alt=\"\" class=\"intrested-job-logo\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"location-instrested-job\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/location.png\" alt=\"NA\" class=\"location-ins\" />\r\n");
      out.write("          <div class=\"location-name\">\r\n");
      out.write("            <p class=\"paragraph\">Temp. WFH - Mumbai</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"all-about-intrested-job\">\r\n");
      out.write("          <div class=\"company-name-job-name\">\r\n");
      out.write("            <h5 class=\"job-name-of-intrested-job\">\r\n");
      out.write("              Business Development Executive:&nbsp;\r\n");
      out.write("            </h5>\r\n");
      out.write("            <h5 class=\"company-name-of-intrested-comp\">ICICI Bank</h5>\r\n");
      out.write("            <div class=\"Job-basic-details\">\r\n");
      out.write("              <div class=\"rating\">\r\n");
      out.write("                <label></label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h6 class=\"Review\">4.0 | 335223 Review</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"intrested-job-logo-div\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/netflix.png\" alt=\"\" class=\"intrested-job-logo\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"location-instrested-job\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/location.png\" alt=\"NA\" class=\"location-ins\" />\r\n");
      out.write("          <div class=\"location-name\">\r\n");
      out.write("            <p class=\"paragraph\">Temp. WFH - Mumbai</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"all-about-intrested-job\">\r\n");
      out.write("          <div class=\"company-name-job-name\">\r\n");
      out.write("            <h5 class=\"job-name-of-intrested-job\">\r\n");
      out.write("              Business Development Executive:&nbsp;\r\n");
      out.write("            </h5>\r\n");
      out.write("            <h5 class=\"company-name-of-intrested-comp\">ICICI Bank</h5>\r\n");
      out.write("            <div class=\"Job-basic-details\">\r\n");
      out.write("              <div class=\"rating\">\r\n");
      out.write("                <label></label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h6 class=\"Review\">4.0 | 335223 Review</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"intrested-job-logo-div\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/netflix.png\" alt=\"\" class=\"intrested-job-logo\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"location-instrested-job\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/location.png\" alt=\"NA\" class=\"location-ins\" />\r\n");
      out.write("          <div class=\"location-name\">\r\n");
      out.write("            <p class=\"paragraph\">Temp. WFH - Mumbai</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"view-all\">\r\n");
      out.write("          <button class=\"Infrastructure\" role=\"button\">View all</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br />\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"custom-right-sub\">\r\n");
      out.write("        <div class=\"full-review-container\">\r\n");
      out.write("          <div class=\"review-and-read-all-view\">\r\n");
      out.write("            <h4 class=\"right-container-headings\">Reviews</h4>\r\n");
      out.write("            <a class=\"read-all-review\" href=\"#\">Read all 34524 reviews</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <h5 class=\"job-name-of-intrested-job\">\r\n");
      out.write("            Business Development Executive:&nbsp;\r\n");
      out.write("          </h5>\r\n");
      out.write("          <div>\r\n");
      out.write("            <p class=\"review-by-and-time\">Anonymous | 04 Feb 2023</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"rating\">\r\n");
      out.write("            <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label for=\"star5\"></label>\r\n");
      out.write("            <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label for=\"star4\"></label>\r\n");
      out.write("            <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label for=\"star3\"></label>\r\n");
      out.write("            <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label for=\"star2\"></label>\r\n");
      out.write("            <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label for=\"star1\"></label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <h5 class=\"Likes-of-intrested-job\">Likes</h5>\r\n");
      out.write("          <div class=\"comment\">\r\n");
      out.write("            it's a good to start as a fresher. You can ask doubt to senior\r\n");
      out.write("            members if you're struggling\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"custom-right-sub\">\r\n");
      out.write("        <div class=\"review-and-read-all-view\">\r\n");
      out.write("          <h4 class=\"right-container-headings\">Benefit & Perks</h4>\r\n");
      out.write("          <a class=\"read-all-review\" href=\"#\">Read all 34524 reviews</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"reported-benefit\">3 User reported these benefit</p>\r\n");
      out.write("        <br />\r\n");
      out.write("        <div class=\"all-benefit\">\r\n");
      out.write("          <div class=\"continer-of-benefit\">\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/home.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Work from home</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/group.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Soft Skill Training</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/online-training.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Job Training</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"continer-of-benefit\">\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/beach-chair.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Team Outing</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/car.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Transport</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-benefit\">\r\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/diner.png\" alt=\"NA\" class=\"img-of-benefit\" />\r\n");
      out.write("              <p class=\"benefit-name\">Fresh Food</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"custom-right-sub\">\r\n");
      out.write("        <div class=\"review-and-read-all-view\">\r\n");
      out.write("          <h4 class=\"right-container-headings\">\r\n");
      out.write("            Service you might be intrested\r\n");
      out.write("          </h4>\r\n");
      out.write("          <a class=\"read-all-review\" href=\"#\">Know more</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"service-name\">Resume Display</p>\r\n");
      out.write("        <h5 class=\"service-desc\">\r\n");
      out.write("          Increase your profile visiblity to recurite upto 3 times\r\n");
      out.write("        </h5>\r\n");
      out.write("        <h5 class=\"service-desc-more\">\r\n");
      out.write("          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum,\r\n");
      out.write("          suscipit laboriosam id eius distinctio esse! Nisi\r\n");
      out.write("        </h5>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"border\"></div>\r\n");
      out.write("        <br />\r\n");
      out.write("        &nbsp;\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/Random.jfif\" alt=\"NA\" class=\"service-intrested-provider\" />\r\n");
      out.write("        <br />\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <footer>Footer</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
